azuread_application attribute application_id has been deprecated
claranet/terraform-azurerm-service-principal pull request #1
Opened 2023-11-15 18:51 UTC by mloskot

Follow-up to the following update in version 2.45.0 of hashicorp/terraform-provider-azuread,
as per https://github.com/hashicorp/terraform-provider-azuread/pull/1214

> `azuread_application` - export the client_id attribute,
> deprecate the `application_id` attribute

The `terraform validate` also issues the following warning for version 7.2.1 of this module:

```
│ Warning: Deprecated attribute
│
│   on .terraform/modules/sp/outputs.tf line 8, in output "sp_app_id":
│    8:   value       = azuread_application.aad_app.application_id
│
│ The attribute "application_id" is deprecated. Refer to the provider documentation for details.
```

Fixes #(issue) .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes proposed in this pull request

-
-
-

@claranet/fr-azure-reviewers

2023-11-16 08:14 UTC, BzSpi requested changes, later dismissed
Thank you for this contribution.

Please bump the provider version to 2.44 in the `versions.tf` file.

2023-11-16 09:17 UTC, Shr3ps requested changes
Can you also update the CHANGELOG file?

2023-11-17 10:21 UTC, Shr3ps approved these changes

2023-11-17 10:22 UTC, jmapro approved these changes

2023-11-17 10:23 UTC, maxpoullain approved these changes

2023-11-17 10:24 UTC, zfiel approved these changes

2023-11-17 10:29 UTC, merged

2023-11-17 12:08 UTC, mloskot commented
Thanks!